version: "3"

services:
  kutt:
    build:
      context: ./kutt
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
      # env_file:
      #- ./kutt/.env
    # ports:
    #   - 3000:3000
    # networks:
    #   vpcbr:
    #     ipv4_address: 172.22.0.5
    deploy:
     replicas: 3

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - redis_data:/data
    # networks:
    #   vpcbr:

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   vpcbr:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - kutt
    # networks:
    #   vpcbr:

volumes:
  redis_data:
  postgres_data:
# networks:
#   vpcbr:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.22.0.0/16
#           gateway: 172.22.0.1
