version: "3"

services:
  kutt:
    build:
      context: ./kutt
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    env_file:
      - ./kutt/.env
    deploy:
     replicas: 3

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes:
      - redis_data:/data

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - kutt

volumes:
  redis_data:
  postgres_data:
